# TensorFlow Quickstart

Getting started with neural network machine learning models in TensorFlow.

## Set up TensorFlow

In [3]:
# pip3 install tensorflow

In [4]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.13.0


## Load a dataset

In [6]:
# Load and prepare the MNIST dataset. The pixel values of the images range from 0 through 255.
# Scale these values to a range of 0 to 1 by dividing the values by 255.0.
# This also converts the sample data from integers to floating-point numbers:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [19]:
# You can preview the raw data prior to training the model
print(mnist.load_data())

((array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ...

## Build a machine learning model

In [7]:
# Build a tf.keras.Sequential model:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [8]:
# For each example, the model returns a vector of logits or log-odds scores, one for each class.
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.28218323, -0.2626474 , -0.16938315,  0.15272117, -0.2957897 ,
        -0.0528494 ,  0.02909562,  0.06403146,  0.67431676, -0.35960984]],
      dtype=float32)

In [9]:
# The tf.nn.softmax function converts these logits to probabilities for each class: 
tf.nn.softmax(predictions).numpy()

array([[0.12565382, 0.07287167, 0.07999501, 0.1103954 , 0.07049612,
        0.08988202, 0.0975576 , 0.1010261 , 0.18598464, 0.0661376 ]],
      dtype=float32)

In [10]:
# Define a loss function for training using losses.SparseCategoricalCrossentropy:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [12]:
# Configure and compile the model
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])


## Train and evaluate your model

In [13]:
# Use the Model.fit method to adjust your model parameters and minimize the loss: 
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 1s 509us/step - loss: 0.3016 - accuracy: 0.9124
Epoch 2/5
1875/1875 [==============================] - 1s 514us/step - loss: 0.1462 - accuracy: 0.9572
Epoch 3/5
1875/1875 [==============================] - 1s 505us/step - loss: 0.1087 - accuracy: 0.9663
Epoch 4/5
1875/1875 [==============================] - 1s 512us/step - loss: 0.0893 - accuracy: 0.9718
Epoch 5/5
1875/1875 [==============================] - 1s 499us/step - loss: 0.0774 - accuracy: 0.9758


In [14]:
# The Model.evaluate method checks the model's performance, usually on a validation set or test set.
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0790 - accuracy: 0.9757 - 126ms/epoch - 403us/step


[0.07904709875583649, 0.9757000207901001]

In [15]:
# If you want your model to return a probability, you can wrap the trained model, and attach the softmax to it:

probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.1381442e-07, 1.2493059e-08, 4.6679975e-06, 5.0975598e-04,
        2.3767580e-10, 8.8744054e-07, 5.8283575e-13, 9.9947828e-01,
        4.8932998e-07, 5.7814891e-06],
       [1.6270951e-08, 3.1651885e-05, 9.9994957e-01, 1.1931742e-05,
        4.2942398e-15, 9.1026629e-07, 1.0364544e-06, 8.1141607e-17,
        4.9234400e-06, 7.9949551e-15],
       [1.7301611e-06, 9.9930012e-01, 5.5941098e-05, 2.8840779e-05,
        8.1860111e-05, 3.5271249e-05, 8.1873928e-05, 2.4437119e-04,
        1.6496866e-04, 5.0269696e-06],
       [9.9992669e-01, 4.8858471e-08, 1.1441392e-05, 2.0616257e-07,
        5.4289058e-07, 6.2358333e-07, 7.2935950e-06, 5.1983669e-05,
        3.5523688e-09, 1.0397144e-06],
       [4.4057975e-07, 7.7009216e-10, 7.9363446e-07, 5.2758939e-08,
        9.9748683e-01, 9.6599024e-08, 8.6932334e-07, 1.1146701e-05,
        5.3453311e-07, 2.4991999e-03]], dtype=float32)>